# Header

menu:
  主页: /
  技术: /tags/技术/
  随想: /tags/随想/
  音乐: "http://music.163.com/#/my/m/music/playlist?id=769698716"

# SubNav
subnav:
  github: "https://github.com/AwenZeng"
  weibo: "http://weibo.com/awenyini"
  #rss: "http://awenyini.lofter.com"
  mail: "mailto:awenyini@foxmail.com"
  #music: "http://music.163.com/#/playlist?id=1988765233"

  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  #mail: "mailto:litten225@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
fancybox: true
# 数学公式
mathjax: false


# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true

# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '感谢认可，么么哒'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /assets/img/alipay.jpg
# 微信二维码图片地址
weixin: /assets/img/wechat_pay.jpg


# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# 是否在新窗口打开链接
open_in_new: true


# Miscellaneous
baidu_analytics: 'd530997b493cbd89c07d5f435ece780b'
google_analytics: false
favicon: /assets/img/avatar.ico

#你的头像url
avatar: /assets/img/avatar.jpg

#是否开启分享
share_jia: true

mobile:
  social: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus 不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
#duoshuo: "litten-hexo"

#2、网易云跟帖
#wangyiyun: '2dba06fbf8d24c13915ea6c6aa7183b1'

#3、畅言
#changyan_appid: 'cysX3aGWt'
#changyan_conf: 'prod_1dcda447175aada96edcdb7e412338fa'

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '其他'
#  aboutme: 'Me'

friends:
  风光摄影: http://awenyini.lofter.com/
  星空摄影: http://awenstarsky.lofter.com/
  人像摄影: http://awenfigure.lofter.com/
  学习站点: https://awenzeng.github.io/2017/03/17/tech_study_website/

aboutme: 我是笔沫拾光.<br><br>独立，喜欢思考，喜欢摄影，喜欢码代码。<br><br>Motto:感悟生命的意义，体验人生的美好！创造回忆，回忆人生。<br>
