# Header

menu:
  主页: /
  随想: /tags/随想/
  技术: /tags/技术/
  旅行: /tags/摄影/

# SubNav
subnav:
  github: "https://github.com/AwenZeng"
  weibo: "http://weibo.com/awenyini"
  #rss: "http://awenyini.lofter.com"
  mail: "mailto:awenyini@foxmail.com"
 # zhihu: "#"

  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"

  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root:

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true

# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '感谢认可，么么哒'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /assets/img/alipay.jpg
# 微信二维码图片地址
weixin: /assets/img/wechat_pay.jpg

# Miscellaneous
baidu_analytics: 'd530997b493cbd89c07d5f435ece780b'
google_analytics: ''
favicon: /assets/img/avatar.ico

#你的头像url
avatar: /assets/img/avatar.jpg

#是否开启分享
share_jia: true

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: awenzeng

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '其他'
#  aboutme: 'Me'

friends:
  风光摄影: http://awenyini.lofter.com/
  星空摄影: http://awenstarsky.lofter.com/
  人像摄影: http://awenfigure.lofter.com/
  学习站点: https://awenzeng.github.io/2017/03/17/tech_study_website/

aboutme: 我是笔沫拾光.<br><br>独立，喜欢思考，喜欢摄影，喜欢码代码。<br><br>Motto:感悟生命的意义，体验人生的美好！创造回忆，回忆人生。<br>
